w04/d05/Richard/band_app/config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :bands do
    resources :events
  end

  resources :venues do
    resources :events
  end

  resources :events

end

w04/d05/Richard/band_app/app/models/band.rb
class Band < ActiveRecord::Base
  has_many :events
end

w04/d05/Richard/band_app/app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :band
  belongs_to :venue

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where(:venue_id, "%#{query}%")

  end
end

w04/d05/Richard/band_app/app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :events
end

w04/d05/Richard/band_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    redirect_to '/events'
  end

  def new
    @band = Band.new
  end

  def create
    @band=Band.create(band_params)
    redirect_to @band
  end

  def show
    @band = Band.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def find_venue
    @band = Band.find(params[:id])
  end

  def band_params
    params.require(:band).permit(:name, :genre, :explicit_lyrics, :video_embed_url)
  end

end

w04/d05/Richard/band_app/app/controllers/events_controller.rb
class EventsController < ApplicationController

def index
 @venue= Venue.all
  @band = Band.all
  if params[:search]
    @events = Event.search(params[:search])
  else
    @events = Event.all
  end
end

  def new
    @event = Event.new
    @band = Band.all
    @venue = Venue.all
  end

  def create
    @event=Event.create(event_params)
    redirect_to @event
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def find_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:date, :time, :band_id, :venue_id)
  end

end

w04/d05/Richard/band_app/app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  def index
    redirect_to '/events'
  end

  def new
    @venue = Venue.new
  end

  def create
    @venue=Venue.create(venue_params)
    redirect_to @venue
  end

  def show
    @venue = Venue.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def find_venue
    @venue = Venue.find(params[:id])
  end

  def venue_params
    params.require(:venue).permit(:name, :city, :state, :allows_explicit_lyrics)
  end

end

w04/d05/Richard/band_app/app/helpers/application_helper.rb
module ApplicationHelper

def us_states
  [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
end


      def find_band
        band_name = Band.all
          bands_name = band_name.map do |band|
            [band.name, band.id]
          end
          bands_name
      end

      def find_venue
        venue_name = Venue.all
          venues_name = venue_name.map do |venue|
            [venue.name, venue.id]
          end
          venues_name
      end

end

w04/d05/Richard/band_app/app/views/events/_manage_form.html.erb
<%= form_for @event do |f| %>
  <%=f.label :date %>
  <%= f.date_select :date %>

  <%=f.label :time %>
  <%= f.time_select :time %>

  <%=f.label :band_id %>
  <%=f.select :band_id, options_for_select(find_band)%>

  <%=f.label :venue_id %>
  <%=f.select :venue_id, options_for_select(find_venue)%>

  <%= f.submit "Add new event" %>
<% end %>

w04/d05/Richard/band_app/app/views/events/index.html.erb
<%= link_to "All Venues", venues_path %>


<%= form_tag(venue_events_path(@venue), :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Events" %>
<%= submit_tag "Search" %>
<% end %>


<h1>Venues</h1>

<ul>
  <% @venue.each do |venue| %>
  <li><%= link_to venue.name, venue %></li>
  <% end %>
</ul>

<ul>
  <% @band.each do |band| %>
  <li><%= link_to band.name, band %></li>
  <% end %>
</ul>

w04/d05/Richard/band_app/app/views/events/new.html.erb
<h1>Add an Event</h1>

<!-- Hero Add Form -->

<%= render "manage_form" %>


<!-- Cancel -->

<p><%= link_to "Cancel", venues_path %></p>

w04/d05/Richard/band_app/app/views/events/show.html.erb
<h1><%= @venue.name %></h1>
<p><%= @venue.city %>, <%= @venue.state %></p>


<h1><%= @band.name %></h1>
<p>Here's a sample of their work!<br>
  <iframe width="560" height="315" src="//www.youtube.com/embed/<%= @band.video_embed_url%>" frameborder="0" allowfullscreen></iframe></p>